# Copyright (C) 2020 Panther Labs Inc
#
# Panther Enterprise is licensed under the terms of a commercial license available from
# Panther Labs Inc ("Panther Commercial License") by contacting contact@runpanther.com.
# All use, distribution, and/or modification of this software, whether commercial or non-commercial,
# falls under the Panther Commercial License to the extent it is permitted.



variable "aws_partition" {
  type        = string
  default     = "aws"
  description = "aws, aws-cn, or aws-us-gov"
}

variable "aws_account_id" {
  type        = string
  description = "12-digit AWS account ID where Panther will be deployed"
}

variable "assume_role_principal" {
  type        = string
  default     = ""
  description = "IAM principal allowed to assume the deployment role (defaults to aws_account_id)"
}

variable "deployment_role_name" {
  type        = string
  default     = "PantherDeploymentRole"
  description = "The name of the deployment IAM role. If blank, the name will be autogenerated"
}
