# Copyright (C) 2022 Panther Labs, Inc.
#
# The Panther SaaS is licensed under the terms of the Panther Enterprise Subscription
# Agreement available at https://panther.com/enterprise-subscription-agreement/.
# All intellectual property rights in and to the Panther SaaS, including any and all
# rights to access the Panther SaaS, are governed by the Panther Enterprise Subscription Agreement.



variable "aws_partition" {
  type        = string
  default     = "aws"
  description = "aws, aws-cn, or aws-us-gov"
}

variable "aws_account_id" {
  type        = string
  description = "12-digit AWS account ID where Panther will be deployed"
}

variable "assume_role_principal" {
  type        = string
  default     = ""
  description = "IAM principal allowed to assume the deployment role (defaults to aws_account_id)"
}

variable "deployment_role_name" {
  type        = string
  default     = "PantherDeploymentRole"
  description = "The name of the deployment IAM role. If blank, the name will be autogenerated"
}
