variable "aws_partition" {
  type        = string
  default     = "aws"
  description = "aws, aws-cn, or aws-us-gov"
}

variable "aws_account_id" {
  type        = string
  description = "12-digit AWS account ID where Panther will be deployed"
}

variable "assume_role_principal" {
  type        = string
  default     = ""
  description = "IAM principal allowed to assume the deployment role (defaults to aws_account_id)"
}

variable "deployment_role_name" {
  type        = string
  default     = "PantherDeploymentRole"
  description = "The name of the deployment IAM role. If blank, the name will be autogenerated"
}
