# Copyright (C) 2022 Panther Labs Inc
#
# Panther Enterprise is licensed under the terms of a commercial license available from
# Panther Labs Inc ("Panther Commercial License") by contacting contact@runpanther.com.
# All use, distribution, and/or modification of this software, whether commercial or non-commercial,
# falls under the Panther Commercial License to the extent it is permitted.

AWSTemplateFormatVersion: 2010-09-09
Description: Sets up an SNS topic and subscribes the Panther Log processing SQS queue to it.

Parameters:
  SnsTopicName:
    Type: String
    Description: The name of the new SNS Topic to create for receiving S3 notifications
    Default: panther-notifications-topic
  SnsLogProcessingCmkMgmtRoleArn:
    Type: String
    Description: The ARN of the role that manages the KMS CMK used by the SNS topic
    Default: ''
    # Defaults to :root (all identities) in satellite account
    # To restrict access to the key, use an existing role (not managed by this template)
    # to manage the KMS CMK used by the SNS topic
    # Unless you use a dedicated key management role, this will be the role
    # you use in the AWS console or the role used in your template deployment
    # pipeline
  MasterAccountId:
    Type: String
    Description: The AWS Account ID of the Panther deployment
  PantherRegion:
    Type: String
    Description: The AWS Region of the Panther deployment
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ap-east-1
      - ap-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-north-1
      - me-south-1
      - sa-east-1
      # AWS China Regions
      - cn-north-1
      - cn-northwest-1
      # AWS Gov Cloud
      - us-gov-east-1
      - us-gov-west-1

Conditions:
  MgmtRoleProvided: !Not [!Equals ['', !Ref SnsLogProcessingCmkMgmtRoleArn]]

Resources:
  # This topic is used to notify the Panther master account whenever new data is written to the
  # LogProcessing bucket.
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref SnsTopicName
      KmsMasterKeyId: !Ref PantherLogProcessingKey

  # This policy is used to allow S3 to publish to the topic when new data is written to S3
  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          # Reference: https://amzn.to/2ouFmhK
          - Sid: AllowS3EventNotifications
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref Topic
          - Sid: AllowCloudTrailNotification
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: sns:Publish
            Resource: !Ref Topic
          - Sid: AllowSubscriptionToPanther
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${MasterAccountId}:root
            Action: sns:Subscribe
            Resource: !Ref Topic
      Topics:
        - !Ref Topic

  # SNS Topic subscription to Panther
  Subscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Sub arn:${AWS::Partition}:sqs:${PantherRegion}:${MasterAccountId}:panther-input-data-notifications-queue
      Protocol: sqs
      RawMessageDelivery: false
      TopicArn: !Ref Topic

  PantherLogProcessingKey:
    Type: AWS::KMS::Key
    Properties:
      Description: The Panther log processing customer-managed CMK
      KeyPolicy:
        Version: '2012-10-17'
        Id: panther-log-processing-cmk
        Statement:
          - Sid: S3CloudTrailSNSPublish
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
                - cloudtrail.amazonaws.com
            Action:
              - kms:GenerateDataKey
              - kms:Decrypt
            Resource: '*'
          - Sid: KeyManagement
            Effect: Allow
            Principal:
              AWS: !If
                - MgmtRoleProvided
                - !Ref SnsLogProcessingCmkMgmtRoleArn
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
            Resource: '*'

  PantherEventsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/panther-log-processing
      TargetKeyId: !Ref PantherLogProcessingKey

Outputs:
  SnsTopicArn:
    Description: The ARN of the SNS Topic that will be notifying Panther of new data.
    Value: !Ref Topic
