# Copyright (C) 2022 Panther Labs, Inc.
#
# The Panther SaaS is licensed under the terms of the Panther Enterprise Subscription
# Agreement available at https://panther.com/enterprise-subscription-agreement/.
# All intellectual property rights in and to the Panther SaaS, including any and all
# rights to access the Panther SaaS, are governed by the Panther Enterprise Subscription Agreement.

AWSTemplateFormatVersion: 2010-09-09
Description: IAM roles for creating and updating a lookup table from an S3 object.

Mappings:
  PantherParameters:
    MasterAccountId:
      Value: '' # Panther AWS Account ID
    RoleSuffix:
      Value: '' # Unique suffix to differentiate from other roles
    S3Bucket:
      Value: '' # Name of the S3 bucket containing the LUT file
    S3Object:
      Value: '' # Name of the object (including path) containing the LUT data, defaults to greynoise_noise_lut.jsonl
    KmsKey:
      Value: '' # (Optional) ARN of the KMS Key encrypting the object

Parameters:
  # Required parameters
  MasterAccountId:
    Type: String
    Description: Panther AWS Account ID. Only fill out if you did not update the mappings.
    Default: ''
  RoleSuffix:
    Type: String
    Description: Unique suffix to differentiate from other roles. Only fill out if you did not update the mappings.
    Default: ''
  S3Bucket:
    Type: String
    Description: Name of the S3 bucket containing the LUT file. Only fill out if you did not update the mappings.
    Default: ''
  S3Object:
    Type: String
    Description: Name of the object (including path) containing the LUT data. Only fill out if you did not update the mappings.
    Default: ''

  # Optional configuration parameters
  KmsKey:
    Type: String
    Description: (Optional) ARN of the KMS Key encrypting the object. Only fill out if you did not update the mappings.
    Default: ''

Conditions:
  # Condition to define if the template is generated by panther backend
  IsGenerated: !Not [!Equals ['', !FindInMap [PantherParameters, MasterAccountId, Value]]]
  # Condition whether the generated template has KMS key
  GeneratedKmsKeySetup: !Not [!Equals ['', !FindInMap [PantherParameters, KmsKey, Value]]]

  # Condition whether the default template values has KMS key
  DefaultKmsKeySetup: !Not [!Equals ['', !Ref KmsKey]]

  # Condition whether we should add KMS key permissions
  IncludeKmsKey: !Or
    - !And [Condition: IsGenerated, Condition: GeneratedKmsKeySetup]
    - !And [!Not [Condition: IsGenerated], Condition: DefaultKmsKeySetup]

Resources:
  LookupsS3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - PantherLUTsRole-${Suffix}
        - Suffix: !If
            - IsGenerated
            - !FindInMap [PantherParameters, RoleSuffix, Value]
            - !Ref RoleSuffix
      MaxSessionDuration: 3600 # 1 hour
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub
                - arn:${AWS::Partition}:iam::${AccountId}:root
                - AccountId:
                    !If [
                      IsGenerated,
                      !FindInMap [PantherParameters, MasterAccountId, Value],
                      !Ref MasterAccountId,
                    ]
            Action: sts:AssumeRole
            Condition:
              Bool:
                aws:SecureTransport: true
      Policies:
        - PolicyName: ReadData
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:GetBucketLocation
                Resource: !Sub
                  - arn:${AWS::Partition}:s3:::${Bucket}
                  - Bucket:
                      !If [
                        IsGenerated,
                        !FindInMap [PantherParameters, S3Bucket, Value],
                        !Ref S3Bucket,
                      ]
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub
                  - arn:${AWS::Partition}:s3:::${Bucket}/${Key}
                  - Bucket:
                      !If [
                        IsGenerated,
                        !FindInMap [PantherParameters, S3Bucket, Value],
                        !Ref S3Bucket,
                      ]
                    Key:
                      !If [
                        IsGenerated,
                        !FindInMap [PantherParameters, S3Object, Value],
                        !Ref S3Object,
                      ]
              - !If
                - IncludeKmsKey
                - !If
                  - IsGenerated
                  - Effect: Allow
                    Action:
                      - kms:Decrypt
                      - kms:DescribeKey
                    Resource: !FindInMap [PantherParameters, KmsKey, Value]
                  - Effect: Allow
                    Action:
                      - kms:Decrypt
                      - kms:DescribeKey
                    Resource: !Ref KmsKey
                - !Ref AWS::NoValue
      Tags:
        - Key: Application
          Value: Panther

Outputs:
  RoleARN:
    Description: The ARN of the lookups S3 role that Panther will use to read s3 objects for updating lookup tables
    Value: !GetAtt LookupsS3Role.Arn
