on: push

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: 3.11
      - name: Install cfn-lint
        run: pip install cfn-lint==0.85.1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e
        with:
          terraform_version: 1.3.4
      - name: Setup tflint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93
      - name: Run terraform fmt
        run: terraform fmt -check -recursive ./terraform
      - name: Run tflint
        run: |
          pushd terraform
          tflint --recursive --disable-rule=terraform_required_version --disable-rule=terraform_required_providers
          popd
      - name: Run cfn-lint
        run: cfn-lint -i W3045,E3030 -- cloudformation/*.yml
